In [1]:
import pandas as pd
import pandas as pd
import numpy as np
import requests

from sqlalchemy import create_engine
from census import Census

# API call for Cencus data

In [2]:
from config import api_key
c = Census(api_key, year=2016)

In [3]:
census_data = c.acs5.get(("NAME", "B19013_001E", "B01003_001E", "B01002_001E",
                          "B19301_001E",
                          "B17001_002E"), {'for': 'zip code tabulation area:*'})

census_pd = pd.DataFrame(census_data)

census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01002_001E": "Median Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",
                                      "B17001_002E": "Poverty Count",
                                      "NAME": "Name", "zip code tabulation area": "Zip Code"})

census_pd = census_pd[["Zip Code", "Population", "Median Age", "Household Income",
                       "Per Capita Income", "Poverty Count"]]



census_pd.to_csv("census_data.csv", index=False)

# Clean up census file

In [4]:
census_file = pd.read_csv('census_data.csv')

census_pd = pd.DataFrame(census_file)
census_pd[census_pd <= 0] = np.nan
census_pd.dropna(axis=0, how='any',inplace=True)
census_pd.head()

,Zip Code,Population,Median Age,Household Income,Per Capita Income,Poverty Count
0,5762,513.0,39.2,58558.0,24235.0,50.0
1,5763,2715.0,43.9,54968.0,29674.0,488.0
2,5764,3370.0,41.3,44468.0,22651.0,323.0
3,5765,1632.0,46.7,56771.0,30786.0,85.0
4,5766,598.0,45.9,52250.0,33227.0,76.0

In [5]:
slim_cencus_pd = census_pd[['Zip Code', 'Population', 'Median Age','Household Income']]
slim_cencus_pd = slim_cencus_pd.rename(columns={'Zip Code':'zipcode',
                                                'Population':'population',
                                                'Median Age':'median_age',
                                                'Household Income':'household_income'
                                   })

slim_cencus_pd.to_csv("cleaned_census_data.csv",index=False)
slim_cencus_pd.head()

   zipcode  population  median_age  household_income
0     5762       513.0        39.2           58558.0
1     5763      2715.0        43.9           54968.0
2     5764      3370.0        41.3           44468.0
3     5765      1632.0        46.7           56771.0
4     5766       598.0        45.9           52250.0

# Clean up Parks data

In [6]:
parks = pd.read_csv('CPD_Parks.csv')
parks.dropna(inplace=True)
parks['ZIP'] = parks['ZIP'].astype(int)
parks.dtypes

the_geom       object
PARK_NO         int64
OBJECTID_1      int64
PARK           object
LOCATION       object
ZIP             int32
ACRES         float64
WARD            int64
PARK_CLASS     object
LABEL          object
GISOBJID        int64
WHEELCHR_A      int64
ARCHERY_RA      int64
ARTIFICIAL      int64
BAND_SHELL      int64
BASEBALL_B      int64
BASKETBALL      int64
BASKETBA_1      int64
BEACH           int64
BOAT_LAUNC      int64
BOAT_LAU_1      int64
BOAT_SLIPS      int64
BOCCE_COUR      int64
BOWLING_GR      int64
CASTING_PI      int64
FOOTBALL_S      int64
COMMUNITY_      int64
CONSERVATO      int64
CULTURAL_C      int64
DOG_FRIEND      int64
               ...
VOLLEYBALL      int64
SENIOR_CEN      int64
SHUFFLEBOA      int64
SKATE_PARK      int64
SLED_HILL       int64
SPORT_ROLL      int64
SPRAY_FEAT      int64
BASEBALL_S      int64
TENNIS_COU      int64
TRACK           int64
VOLLEYBA_1      int64
WATER_PLAY      int64
WATER_SLID      int64
BOXING_CEN      int64
WETLAND_AR      int64
LAGOON          int64
CRICKET_FI      int64
CLIMBING_W      int64
GAME_TABLE      int64
CAROUSEL        int64
CROQUET         int64
HANDBALL_I      int64
HARBOR          int64
MODELTRAIN      int64
MODELYACHT      int64
NATURE_BIR      int64
MINIGOLF        int64
PERIMETER     float64
Shape_Leng    float64
Shape_Area    float64
Length: 81, dtype: object

In [7]:
parks.groupby('ZIP').first()

,the_geom,PARK_NO,OBJECTID_1,PARK,LOCATION,ACRES,WARD,PARK_CLASS,LABEL,GISOBJID,...,CROQUET,HANDBALL_I,HARBOR,MODELTRAIN,MODELYACHT,NATURE_BIR,MINIGOLF,PERIMETER,Shape_Leng,Shape_Area
ZIP,,,,,,,,,,,,,,,,,,,,,
60602,MULTIPOLYGON (((-87.64972490185481 41.88036562...,542,369,BARTELME (MARY),115 S. SANGAMON ST,2.710000,25,NEIGHBORHOOD PARK,Bartelme,390,...,0,0,0,0,0,0,0,1387.335774,1387.335774,1.181964e+05
60604,MULTIPOLYGON (((-87.62777096994864 41.87780185...,541,368,PRITZKER,301-52 S STATE ST,1.100000,4,PASSIVE PARK,Pritzker,579,...,0,0,0,0,0,0,0,1087.546171,1087.546171,4.980581e+04
60605,MULTIPOLYGON (((-87.61769160625941 41.86508529...,24,22,GRANT (ULYSSES),331 E RANDOLPH ST,295.450000,0,MAGNET PARK,Grant,368,...,0,0,2,0,0,0,0,56098.142373,55248.485247,1.365284e+07
60606,MULTIPOLYGON (((-87.65952916060392 41.88019821...,211,116,SKINNER (MARK),1331 W MONROE ST,5.850000,27,COMMUNITY PARK,Skinner,332,...,0,0,0,0,0,0,0,2238.271821,2238.271821,2.933938e+05
60607,MULTIPOLYGON (((-87.65424890386825 41.87146005...,205,110,SHERIDAN (PHILIP HENRY),910 S ABERDEEN ST,4.440000,25,COMMUNITY PARK,Sheridan,350,...,0,0,0,0,0,0,0,1927.047333,1927.047333,1.933236e+05
60608,MULTIPOLYGON (((-87.64817638700737 41.83972833...,2,1,MCGUANE (JOHN),2901 S POPLAR AVE,10.300000,11,COMMUNITY PARK,McGuane,416,...,0,0,0,0,0,0,0,2672.326627,2672.326627,4.303417e+05
60609,MULTIPOLYGON (((-87.63554759376666 41.81257646...,4,3,FULLER (MELVILLE),331 W 45TH ST,11.310000,3,COMMUNITY PARK,Fuller,448,...,0,0,0,0,0,0,0,2878.428150,2878.428150,4.970767e+05
60610,MULTIPOLYGON (((-87.62707274144576 41.90538054...,105,61,GOUDY (WILLIAM) SQUARE,1255 N ASTOR ST,0.610000,43,MINI-PARK,Goudy Sq,282,...,0,0,0,0,0,0,0,644.637553,644.637553,2.627403e+04
60611,MULTIPOLYGON (((-87.61764830499905 41.89757419...,107,63,LAKE SHORE,254 E CHICAGO AVE,7.200000,2,COMMUNITY PARK,Lake Shore,297,...,0,0,0,0,0,0,0,2877.389897,2877.389897,3.082148e+05
60612,MULTIPOLYGON (((-87.6915595035577 41.874891706...,206,111,ALTGELD (JOHN),515 S WASHTENAW AVE,4.320000,28,COMMUNITY PARK,Altgeld,345,...,0,0,0,0,0,0,0,1866.638344,1866.638344,2.079960e+05
60613,MULTIPOLYGON (((-87.64976142885315 41.95195291...,364,229,GILL (JOSEPH),825 W SHERIDAN RD,2.420000,46,COMMUNITY PARK,Gill,188,...,0,0,0,0,0,0,0,1817.153283,1817.153283,1.050889e+05
60614,MULTIPOLYGON (((-87.62004212064544 41.90106719...,100,58,LINCOLN (ABRAHAM),200 W FULLERTON PKWY,1209.980000,0,MAGNET PARK,Lincoln,16,...,0,0,3,0,0,3,0,230322.558202,229497.443475,5.185099e+07
60615,MULTIPOLYGON (((-87.5965423766298 41.800225927...,279,174,ELM,5215 S WOODLAWN AVE,0.520000,4,PASSIVE PARK,Elm,463,...,0,0,0,0,0,0,0,592.139524,592.139524,2.207327e+04
60616,MULTIPOLYGON (((-87.632863551078 41.8344952755...,3,2,ARMOUR (PHILIP) SQUARE,3309 S SHIELDS AVE,9.050000,11,COMMUNITY PARK,Armour Sq,423,...,0,0,0,0,0,0,0,2484.283006,2484.283006,3.910958e+05
60617,MULTIPOLYGON (((-87.54799250054684 41.74462388...,6,5,RUSSELL (MARTIN) SQUARE,3045 E 83RD ST,10.050000,10,COMMUNITY PARK,Russell Sq,537,...,0,0,0,0,0,0,0,2777.375936,2777.375936,4.351691e+05
60618,MULTIPOLYGON (((-87.71566316949551 41.94115675...,81,47,AVONDALE,3516 W SCHOOL ST,1.310000,35,COMMUNITY PARK,Avondale,219,...,0,0,0,0,0,0,0,1071.642207,1071.642207,5.373947e+04
60619,MULTIPOLYGON (((-87.59926881696089 41.75482727...,15,14,GRAND CROSSING,7655 S INGLESIDE AVE,18.890000,8,REGIONAL PARK,Grand Crossing,530,...,0,0,0,0,0,0,0,3976.462529,3976.462529,8.175010e+05
60620,MULTIPOLYGON (((-87.65847710634861 41.74305144...,26,23,FOSTER (J. FRANK),1400 W 84TH ST,25.200000,21,REGIONAL PARK,Foster,539,...,0,0,0,0,0,0,0,4258.901480,4258.901480,1.095470e+06
60621,MULTIPOLYGON (((-87.63487905765092 41.76344039...,9,8,HAMILTON (ALEXANDER),513 W 72ND ST,28.940000,6,REGIONAL PARK,Hamilton,520,...,0,2,0,0,0,0,0,4589.617571,4589.617571,1.258960e+06
60622,MULTIPOLYGON (((-87.66204836182995 41.89623330...,208,113,ECKHART (BERNARD),1330 W CHICAGO AVE,8.850000,27,COMMUNITY PARK,Eckhart,296,...,0,0,0,0,0,0,0,2465.242191,2465.242191,3.853956e+05
60623,MULTIPOLYGON (((-87.72368148644935 41.86095958...,355,223,NINEBARK,1447-1453 S HARDING AVE,0.250000,24,MINI-PARK,Ninebark,339,...,0,0,0,0,0,0,0,510.790663,510.790663,1.607286e+04
60624,MULTIPOLYGON (((-87.71602281440826 41.88077398...,204,109,GARFIELD (JAMES),100 N CENTRAL PARK DR,175.900000,28,CITYWIDE PARK,Garfield,334,...,0,0,0,0,0,0,0,19969.373820,19969.373819,7.516840e+06
60625,MULTIPOLYGON (((-87.72746880126329 41.97547835...,41,29,FIELD (EUGENE),5100 N RIDGEWAY AVE,17.822277,39,COMMUNITY PARK,Field,19,...,0,0,0,0,0,0,0,11613.923480,11613.923480,8.284892e+05
60626,MULTIPOLYGON (((-87.66213474862596 42.01283457...,115,67,LOYOLA,1230 W GREENLEAF AVE,40.540000,49,REGIONAL PARK,Loyola,59,...,0,0,0,0,0,1,0,8248.376660,8248.376660,1.780483e+06
60627,MULTIPOLYGON (((-87.59692997312719 41.65371929...,255,152,CARVER (GEORGE WASHINGTON),939 E 132ND ST,18.760000,9,REGIONAL PARK,Carver,374,...,0,0,0,0,0,0,0,5589.990573,5589.990573,8.486209e+05
60628,MULTIPOLYGON (((-87.61806854778479 41.68906488...,13,12,PALMER (POTTER),200 E 111TH ST,38.440000,9,REGIONAL PARK,Palmer,150,...,0,0,0,0,0,0,0,5156.791143,5156.791143,1.674187e+06
60629,MULTIPOLYGON (((-87.7022486538381 41.764478266...,10,9,MARQUETTE (JACQUES),6734 S KEDZIE AVE,315.630000,17,CITYWIDE PARK,Marquette,30,...,0,0,0,0,0,2,0,16520.041317,16520.041317,1.373150e+07
60630,MULTIPOLYGON (((-87.7283832230877 41.975433243...,40,28,GOMPERS (SAMUEL),4222 W FOSTER AVE,38.240000,39,REGIONAL PARK,Gompers,114,...,0,0,0,0,0,0,0,11806.979778,11806.979778,1.836666e+06
60631,MULTIPOLYGON (((-87.81771794429906 42.00133286...,57,37,MONUMENT,6700 N AVONDALE AVE,1.610000,41,NEIGHBORHOOD PARK,Monument,76,...,0,0,0,0,0,0,0,1087.554497,1087.554496,7.210835e+04
60632,MULTIPOLYGON (((-87.73396496749032 41.80586172...,250,149,ARCHER (WILLIAM BEATTY),4901 S KILBOURN AVE,14.090000,14,COMMUNITY PARK,Archer,454,...,0,0,0,0,0,0,0,3524.002599,3524.002599,6.125891e+05
60633,MULTIPOLYGON (((-87.55188135877168 41.65556146...,17,16,MANN (JAMES),3035 E 130TH ST,18.860000,10,REGIONAL PARK,Mann,164,...,0,0,0,0,0,0,0,3840.199967,3840.199967,8.215250e+05
60634,MULTIPOLYGON (((-87.79572532953122 41.93629347...,121,69,"BELL (GEORGE,JR.)",3020 N OAK PARK AVE,4.360000,36,NEIGHBORHOOD PARK,Bell,231,...,0,0,0,0,0,0,0,1843.987956,1843.987956,1.900495e+05
60635,MULTIPOLYGON (((-87.79864707333931 41.92001134...,127,75,RUTHERFORD SAYRE,6871 W BELDEN AVE,13.470000,0,COMMUNITY PARK,Rutherford Sayre,385,...,0,0,0,0,0,0,0,6380.022701,6380.022701,5.767260e+05
60636,MULTIPOLYGON (((-87.6544369431631 41.774541350...,8,7,OGDEN (WILLIAM),6500 S RACINE AVE,57.040000,17,REGIONAL PARK,Ogden,501,...,0,0,0,0,0,0,0,6465.967414,6465.967414,2.518604e+06
60637,MULTIPOLYGON (((-87.60615975027056 41.78725348...,21,19,WASHINGTON (GEORGE),5531 S DR MARTIN LUTHER KING J,350.490000,0,CITYWIDE PARK,Washington (George),36,...,0,1,0,0,0,0,0,22537.534547,22537.534547,1.505621e+07
60638,MULTIPOLYGON (((-87.77765792477558 41.78135090...,234,133,HALE (NATHAN),6140 S MELVINA AVE,17.440000,13,REGIONAL PARK,Hale,495,...,0,0,0,0,0,0,0,3679.288960,3679.288960,7.507904e+05
60639,MULTIPOLYGON (((-87.75124557767934 41.92238486...,122,70,BLACKHAWK,2318 N LAVERGNE AVE,6.880000,36,COMMUNITY PARK,Blackhawk,251,...,0,0,0,0,0,0,0,2208.732707,2208.732707,2.999487e+05
60640,MULTIPOLYGON (((-87.66741954235707 41.96791722...,103,59,CHASE (SALMON),4725 N ASHLAND AV,4.930000,47,COMMUNITY PARK,Chase,125,...,0,0,0,0,0,0,0,1959.639535,1959.639535,2.135509e+05
60641,MULTIPOLYGON (((-87.73730888466743 41.94264454...,84,50,KILBOURN,3501 N KILBOURN AVE,12.080000,30,COMMUNITY PARK,Kilbourn,212,...,0,0,0,0,0,0,0,3426.105415,3426.105415,4.975796e+05
60643,MULTIPOLYGON (((-87.6707122183118 41.693128799...,46,32,BOHN (HENRY),1978 W 111TH ST,1.650000,19,PASSIVE PARK,Bohn,148,...,0,0,0,0,0,0,0,1208.593321,1208.593321,7.113765e+04
60644,MULTIPOLYGON (((-87.76525709483738 41.88921252...,207,112,AUSTIN TOWN HALL,5610 W LAKE ST,3.710000,29,COMMUNITY PARK,Austin Town Hall,324,...,0,0,0,0,0,0,0,1638.376012,1638.376012,1.609284e+05
60645,MULTIPOLYGON (((-87.70468667660909 42.00662215...,273,169,LERNER (LEO),7000 N SACRAMENTO AVE,8.530000,50,COMMUNITY PARK,Lerner,65,...,0,0,0,0,0,0,0,2457.190098,2457.190098,3.697311e+05
60646,MULTIPOLYGON (((-87.78523653475305 41.98966354...,91,54,ROSEDALE,6312 W ROSEDALE AVE,3.070000,45,COMMUNITY PARK,Rosedale,97,...,0,0,0,0,0,0,0,1465.957694,1465.957694,1.313723e+05
60647,MULTIPOLYGON (((-87.72336833641168 41.93174942...,120,68,KOSCIUSZKO (THADEUZ),2732 N AVERS AVE,9.010000,31,COMMUNITY PARK,Kosciuszko,237,...,0,0,0,0,0,0,0,2491.198177,2491.198177,3.921041e+05
60649,MULTIPOLYGON (((-87.5773585654263 41.758770128...,231,130,ROSENBLUM (J. LESLIE),2000 E 75TH ST,10.660000,8,COMMUNITY PARK,Rosenblum,526,...,0,0,0,0,0,0,0,3247.395263,3247.395263,4.501344e+05
60651,MULTIPOLYGON (((-87.75532302001906 41.90412002...,201,106,LA FOLLETTE (ROBERT),1333 N LARAMIE AVE,18.800000,37,REGIONAL PARK,La Follette,283,...,0,0,0,0,0,0,0,3828.952509,3828.952509,8.145820e+05
60652,MULTIPOLYGON (((-87.73016349276995 41.74947250...,33,26,RAINEY (EDWARD),4350 W 79TH ST,14.300000,18,REGIONAL PARK,Rainey,536,...,0,0,0,0,0,0,0,3239.010583,3239.010583,6.204978e+05
60653,MULTIPOLYGON (((-87.6244857580529 41.817059456...,321,197,ASPEN,4237 S WABASH AVE,0.210000,3,MINI-PARK,Aspen,438,...,0,0,0,0,0,0,0,478.687187,478.687187,9.917073e+03
60654,MULTIPOLYGON (((-87.63979742857411 41.89734689...,560,386,WHITE (JESSE),410 W CHICAGO AVE,1.670000,27,COMMUNITY PARK,White (Jesse),567,...,0,0,0,0,0,0,0,1098.432950,1098.432950,7.178465e+04
60655,MULTIPOLYGON (((-87.68113888818496 41.68640748...,48,34,KENNEDY (DENNIS),11320 S WESTERN AVE,18.480000,19,COMMUNITY PARK,Kennedy,155,...,0,0,0,0,0,0,0,3812.723013,3812.723013,8.031703e+05
60656,MULTIPOLYGON (((-87.81437797546035 41.98171622...,59,38,ORIOLE,5430 N OLCOTT AVE,19.470000,41,REGIONAL PARK,Oriole,104,...,0,0,0,0,0,0,0,4550.621989,4550.621989,8.499558e+05
60657,MULTIPOLYGON (((-87.66124976467184 41.93387841...,290,182,SOUTH LAKEVIEW,1300 W WOLFRAM ST,0.800000,32,NEIGHBORHOOD PARK,South Lakeview,235,...,0,0,0,0,0,0,0,779.824820,779.824820,3.409331e+04
60659,MULTIPOLYGON (((-87.71108556977944 41.99021749...,75,45,HOLLYWOOD,3312 W THORNDALE AVE,7.200000,39,COMMUNITY PARK,Hollywood,93,...,0,0,0,0,0,0,0,2236.027243,2236.027243,3.109691e+05
60660,MULTIPOLYGON (((-87.67654310336643 41.99480006...,104,60,EMMERSON (LOUIS),1820 W GRANVILLE AVE,2.680000,40,NEIGHBORHOOD PARK,Emmerson,84,...,0,0,0,0,0,0,0,1915.280699,1915.280699,1.130946e+05
60661,MULTIPOLYGON (((-87.64312008505516 41.87936124...,537,364,HERITAGE GREEN,610-30 W ADAMS ST,1.110000,42,PASSIVE PARK,Heritage Green,382,...,0,0,0,0,0,0,0,867.935942,867.935942,4.636009e+04

In [8]:
parks.count()

the_geom      613
PARK_NO       613
OBJECTID_1    613
PARK          613
LOCATION      613
ZIP           613
ACRES         613
WARD          613
PARK_CLASS    613
LABEL         613
GISOBJID      613
WHEELCHR_A    613
ARCHERY_RA    613
ARTIFICIAL    613
BAND_SHELL    613
BASEBALL_B    613
BASKETBALL    613
BASKETBA_1    613
BEACH         613
BOAT_LAUNC    613
BOAT_LAU_1    613
BOAT_SLIPS    613
BOCCE_COUR    613
BOWLING_GR    613
CASTING_PI    613
FOOTBALL_S    613
COMMUNITY_    613
CONSERVATO    613
CULTURAL_C    613
DOG_FRIEND    613
             ...
VOLLEYBALL    613
SENIOR_CEN    613
SHUFFLEBOA    613
SKATE_PARK    613
SLED_HILL     613
SPORT_ROLL    613
SPRAY_FEAT    613
BASEBALL_S    613
TENNIS_COU    613
TRACK         613
VOLLEYBA_1    613
WATER_PLAY    613
WATER_SLID    613
BOXING_CEN    613
WETLAND_AR    613
LAGOON        613
CRICKET_FI    613
CLIMBING_W    613
GAME_TABLE    613
CAROUSEL      613
CROQUET       613
HANDBALL_I    613
HARBOR        613
MODELTRAIN    613
MODELYACHT    613
NATURE_BIR    613
MINIGOLF      613
PERIMETER     613
Shape_Leng    613
Shape_Area    613
Length: 81, dtype: int64

In [9]:
parks.columns

Index(['the_geom', 'PARK_NO', 'OBJECTID_1', 'PARK', 'LOCATION', 'ZIP', 'ACRES',
       'WARD', 'PARK_CLASS', 'LABEL', 'GISOBJID', 'WHEELCHR_A', 'ARCHERY_RA',
       'ARTIFICIAL', 'BAND_SHELL', 'BASEBALL_B', 'BASKETBALL', 'BASKETBA_1',
       'BEACH', 'BOAT_LAUNC', 'BOAT_LAU_1', 'BOAT_SLIPS', 'BOCCE_COUR',
       'BOWLING_GR', 'CASTING_PI', 'FOOTBALL_S', 'COMMUNITY_', 'CONSERVATO',
       'CULTURAL_C', 'DOG_FRIEND', 'FITNESS_CE', 'FITNESS_CO', 'GALLERY',
       'GARDEN', 'GOLF_COURS', 'GOLF_DRIVI', 'GOLF_PUTTI', 'GYMNASIUM',
       'GYMNASTIC_', 'HANDBALL_R', 'HORSESHOE_', 'ICESKATING', 'POOL_INDOO',
       'BASEBALL_J', 'MOUNTAIN_B', 'NATURE_CEN', 'POOL_OUTDO', 'ZOO',
       'PLAYGROUND', 'PLAYGROU_1', 'ROWING_CLU', 'VOLLEYBALL', 'SENIOR_CEN',
       'SHUFFLEBOA', 'SKATE_PARK', 'SLED_HILL', 'SPORT_ROLL', 'SPRAY_FEAT',
       'BASEBALL_S', 'TENNIS_COU', 'TRACK', 'VOLLEYBA_1', 'WATER_PLAY',
       'WATER_SLID', 'BOXING_CEN', 'WETLAND_AR', 'LAGOON', 'CRICKET_FI',
       'CLIMBING_W', 'GAME_TABLE', 'CAROUSEL', 'CROQUET', 'HANDBALL_I',
       'HARBOR', 'MODELTRAIN', 'MODELYACHT', 'NATURE_BIR', 'MINIGOLF',
       'PERIMETER', 'Shape_Leng', 'Shape_Area'],
      dtype='object')

In [10]:
parks.columns = parks.columns.str.strip().str.capitalize().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
parks.columns

Index(['The_geom', 'Park_no', 'Objectid_1', 'Park', 'Location', 'Zip', 'Acres',
       'Ward', 'Park_class', 'Label', 'Gisobjid', 'Wheelchr_a', 'Archery_ra',
       'Artificial', 'Band_shell', 'Baseball_b', 'Basketball', 'Basketba_1',
       'Beach', 'Boat_launc', 'Boat_lau_1', 'Boat_slips', 'Bocce_cour',
       'Bowling_gr', 'Casting_pi', 'Football_s', 'Community_', 'Conservato',
       'Cultural_c', 'Dog_friend', 'Fitness_ce', 'Fitness_co', 'Gallery',
       'Garden', 'Golf_cours', 'Golf_drivi', 'Golf_putti', 'Gymnasium',
       'Gymnastic_', 'Handball_r', 'Horseshoe_', 'Iceskating', 'Pool_indoo',
       'Baseball_j', 'Mountain_b', 'Nature_cen', 'Pool_outdo', 'Zoo',
       'Playground', 'Playgrou_1', 'Rowing_clu', 'Volleyball', 'Senior_cen',
       'Shuffleboa', 'Skate_park', 'Sled_hill', 'Sport_roll', 'Spray_feat',
       'Baseball_s', 'Tennis_cou', 'Track', 'Volleyba_1', 'Water_play',
       'Water_slid', 'Boxing_cen', 'Wetland_ar', 'Lagoon', 'Cricket_fi',
       'Climbing_w', 'Game_table', 'Carousel', 'Croquet', 'Handball_i',
       'Harbor', 'Modeltrain', 'Modelyacht', 'Nature_bir', 'Minigolf',
       'Perimeter', 'Shape_leng', 'Shape_area'],
      dtype='object')

In [11]:
parks1 = parks.drop(columns=['Park_no','The_geom', 'Objectid_1', 'Park', 'Acres', 'Ward', 'Wheelchr_a', 'Archery_ra', 'Perimeter', 'Shape_leng', 'Shape_area', 'Gisobjid', 'Artificial', 'Band_shell', 'Baseball_b', 'Basketball', 'Basketba_1',
       'Beach', 'Boat_launc', 'Boat_lau_1', 'Boat_slips', 'Bocce_cour',
       'Bowling_gr', 'Casting_pi', 'Football_s', 'Community_', 'Conservato',
       'Cultural_c', 'Dog_friend', 'Fitness_ce', 'Fitness_co', 'Gallery',
       'Garden', 'Golf_cours', 'Golf_drivi', 'Golf_putti', 'Gymnasium',
       'Gymnastic_', 'Handball_r', 'Horseshoe_', 'Iceskating', 'Pool_indoo',
       'Baseball_j', 'Mountain_b', 'Nature_cen', 'Pool_outdo', 'Zoo',
       'Playground', 'Playgrou_1', 'Rowing_clu', 'Volleyball', 'Senior_cen',
       'Shuffleboa', 'Skate_park', 'Sled_hill', 'Sport_roll', 'Spray_feat',
       'Baseball_s', 'Tennis_cou', 'Track', 'Volleyba_1', 'Water_play',
       'Water_slid', 'Boxing_cen', 'Wetland_ar', 'Lagoon', 'Cricket_fi',
       'Climbing_w', 'Game_table', 'Carousel', 'Croquet', 'Handball_i',
       'Harbor', 'Modeltrain', 'Modelyacht', 'Nature_bir', 'Minigolf',
       'Perimeter', 'Shape_leng', 'Shape_area'])
parks1.head()

             Location    Zip      Park_class       Label
0   2901 S POPLAR AVE  60608  COMMUNITY PARK     McGuane
1  3309 S SHIELDS AVE  60616  COMMUNITY PARK   Armour Sq
2       331 W 45TH ST  60609  COMMUNITY PARK      Fuller
3      1809 W 50TH ST  60609  COMMUNITY PARK  Cornell Sq
4      3045 E 83RD ST  60617  COMMUNITY PARK  Russell Sq

In [12]:
parks1 = parks1.rename(columns = {"Zip": "zipcode"})
parks1.head()

             Location  zipcode      Park_class       Label
0   2901 S POPLAR AVE    60608  COMMUNITY PARK     McGuane
1  3309 S SHIELDS AVE    60616  COMMUNITY PARK   Armour Sq
2       331 W 45TH ST    60609  COMMUNITY PARK      Fuller
3      1809 W 50TH ST    60609  COMMUNITY PARK  Cornell Sq
4      3045 E 83RD ST    60617  COMMUNITY PARK  Russell Sq

In [13]:
parks1 = parks1.rename_axis('Park_No')
parks1.head()

                   Location  zipcode      Park_class       Label
Park_No
0         2901 S POPLAR AVE    60608  COMMUNITY PARK     McGuane
1        3309 S SHIELDS AVE    60616  COMMUNITY PARK   Armour Sq
2             331 W 45TH ST    60609  COMMUNITY PARK      Fuller
3            1809 W 50TH ST    60609  COMMUNITY PARK  Cornell Sq
4            3045 E 83RD ST    60617  COMMUNITY PARK  Russell Sq

In [14]:
parks2 = parks1.rename(columns={'Location': 'Address',  'Park_class': 'Park_Class', 'Label':'Park_Name'})
parks2.head()

                    Address  zipcode      Park_Class   Park_Name
Park_No
0         2901 S POPLAR AVE    60608  COMMUNITY PARK     McGuane
1        3309 S SHIELDS AVE    60616  COMMUNITY PARK   Armour Sq
2             331 W 45TH ST    60609  COMMUNITY PARK      Fuller
3            1809 W 50TH ST    60609  COMMUNITY PARK  Cornell Sq
4            3045 E 83RD ST    60617  COMMUNITY PARK  Russell Sq

In [15]:
parks2.to_csv(r'Parks.csv')

In [16]:
updated_parks_pd = pd.read_csv('Parks_3_removed.csv')

# Connect to local database

In [17]:
rds_connection_string = "postgres:Pulmonary#2019@localhost:5432/parks_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [18]:
engine.table_names()

['parks', 'census']

In [19]:
slim_cencus_pd.to_sql(name='census', con=engine, if_exists='append', index=False)

In [20]:
pd.read_sql_query('select * from census', con=engine).head()

   zipcode population median_age household_income
0     5762      513.0       39.2          58558.0
1     5763     2715.0       43.9          54968.0
2     5764     3370.0       41.3          44468.0
3     5765     1632.0       46.7          56771.0
4     5766      598.0       45.9          52250.0

In [21]:
updated_parks_pd.to_sql(name='parks', con=engine, if_exists='append', index=False)

In [22]:
pd.read_sql_query('select * from parks', con=engine).head()

     zip park_no             address      park_class   park_name
0  60608       0   2901 S POPLAR AVE  COMMUNITY PARK     McGuane
1  60616       1  3309 S SHIELDS AVE  COMMUNITY PARK   Armour Sq
2  60609       2       331 W 45TH ST  COMMUNITY PARK      Fuller
3  60609       3      1809 W 50TH ST  COMMUNITY PARK  Cornell Sq
4  60617       4      3045 E 83RD ST  COMMUNITY PARK  Russell Sq